Models/Branch.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace VehicleLeasingApplication.Models
{
    public class Branch
    {
        public int BranchID { get; set; }
        public required string Name { get; set; }
        public required string Location { get; set; }

        [ValidateNever]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }

}

Controllers/BranchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VehicleLeasingApplication.Models;

namespace VehicleLeasingApplication.Controllers
{
    public class BranchesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BranchesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Branches
        public async Task<IActionResult> Index(int page = 1)
        {
            return View(await _context.Branches.ToListAsync());
        }

        // GET: Branches/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = await _context.Branches
                .FirstOrDefaultAsync(m => m.BranchID == id);
            if (branch == null)
            {
                return NotFound();
            }

            return View(branch);
        }

        // GET: Branches/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Branches/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BranchID,Name,Location")] Branch branch)
        {
            Console.WriteLine("Create POST called");

            // This will run no matter what
            if (!ModelState.IsValid)
            {
                Console.WriteLine("ModelState is INVALID!");
                foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                {
                    Console.WriteLine("Validation error: " + error.ErrorMessage);
                }
                return View(branch);
            }

            Console.WriteLine($"Received Name: {branch.Name}, Location: {branch.Location}");

            _context.Add(branch);
            var result = await _context.SaveChangesAsync();
            Console.WriteLine("Save result: " + result);

            return RedirectToAction(nameof(Index));
        }



        // GET: Branches/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = await _context.Branches.FindAsync(id);
            if (branch == null)
            {
                return NotFound();
            }
            return View(branch);
        }

        // POST: Branches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BranchID,Name,Location")] Branch branch)
        {
            if (id != branch.BranchID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(branch);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BranchExists(branch.BranchID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(branch);
        }

        // GET: Branches/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = await _context.Branches
                .FirstOrDefaultAsync(m => m.BranchID == id);
            if (branch == null)
            {
                return NotFound();
            }

            return View(branch);
        }

        // POST: Branches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var branch = await _context.Branches.FindAsync(id);
            if (branch != null)
            {
                _context.Branches.Remove(branch);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BranchExists(int id)
        {
            return _context.Branches.Any(e => e.BranchID == id);
        }
    }
}

Views/Branches/Create.cshtml
@model VehicleLeasingApplication.Models.Branch


@{
    ViewData["Title"] = "Create";
}

<h1>Add NEW Branch</h1>

<h4>Branch</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Branches" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br/>
<div>
    <a asp-action="Index">Back to Branches</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Branches/Delete.cshtml
@model VehicleLeasingApplication.Models.Branch

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Branch</h1>

<h3>Are you sure you want to delete this Branch?</h3>
<div>
    <h4>Branch</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
    </dl>
    <br />
    <form asp-action="Delete">
        <input type="hidden" asp-for="BranchID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to Branches</a>
    </form>
</div>

Views/Branches/Details.cshtml
@model VehicleLeasingApplication.Models.Branch

@{
    ViewData["Title"] = "Details";
}

<h1>Branch Details</h1>

<div>
    <h4>Branch</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
    </dl>
</div>
<br />
<div>
    <a asp-action="Edit" asp-route-id="@Model?.BranchID">Edit</a> |
    <a asp-action="Index">Back to Branches</a>
</div>

Views/Branches/Edit.cshtml
@model VehicleLeasingApplication.Models.Branch

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Branch</h1>

<h4>Branch</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BranchID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index">Back to Branches</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Branches/Index.cshtml
@model IEnumerable<VehicleLeasingApplication.Models.Branch>

@{
    ViewData["Title"] = "Index";
}

<h1>All Branches</h1>

<p>
    <a asp-action="Create">Add New Branch</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.BranchID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.BranchID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.BranchID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Branches/_BranchTablePartial.cshtml
@model IEnumerable<VehicleLeasingApplication.Models.Branch>

@foreach (var item in Model)
{
    <tr>
        <td>@item.Name</td>
        <td>@item.Location</td>
        <td>
            <a asp-action="Edit" asp-route-id="@item.BranchID">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.BranchID">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.BranchID">Delete</a>
        </td>
    </tr>
}